
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 93
#define YY_END_OF_BUFFER 94
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[275] =
    {   0,
        0,    0,   94,   92,   90,   91,   70,   72,   80,   58,
       66,   73,   74,   75,   56,   53,   83,   54,   82,   55,
       46,   46,   85,   84,   61,   63,   59,   87,   87,   87,
       87,   40,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   78,   81,   79,   69,   76,   68,   77,   71,    0,
       52,    0,   65,    0,   51,    0,   57,   46,    0,    0,
        0,   46,    0,    0,    0,   86,   62,   64,   60,   87,
       87,   87,   87,   22,   87,   87,   87,   87,   87,   87,
       87,   87,   87,    0,   87,   87,   87,   41,   87,   87,
       17,   87,   87,   67,   51,    0,    0,    0,   88,   50,

       49,   48,   47,   87,    0,   87,   87,   87,   87,   87,
       87,   87,    0,    5,   87,   87,   87,    0,   87,   87,
        0,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   89,   87,   23,   87,   43,   87,   87,    0,
       87,   87,    0,    0,    0,   87,   87,    0,   31,   87,
        0,   87,   87,   87,   87,   21,   87,   87,   10,   87,
        0,   87,   87,   87,   87,   87,   87,    0,   87,   39,
       24,    0,    0,    0,    0,    0,   87,   87,    0,   87,
       87,    0,   87,   87,   35,   87,   26,   11,   87,    0,
        0,   87,   87,   87,   87,   87,   18,   87,    0,    0,

        0,   20,    0,    0,   87,   87,    0,   87,   87,    0,
       16,   33,   34,   87,   19,    0,   87,   87,   87,   45,
       87,   42,    0,    0,    0,    0,    0,   29,    6,    4,
       32,   87,   12,   14,   37,    0,   87,   87,   87,   27,
        0,    0,   25,    0,   36,   87,    7,   13,   15,    0,
       87,    1,    8,    0,    0,    0,   87,    0,   87,    9,
        0,    0,    0,   30,    2,   38,    0,   44,    0,   28,
        0,    0,    3,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   21,   21,   21,   22,   22,   23,   24,   25,
       26,   27,    1,    1,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   37,   49,   37,   50,
       51,   52,   53,   54,   55,    1,   56,   57,   58,   59,

       60,   61,   62,   63,   64,   37,   37,   65,   66,   67,
       68,   69,   70,   71,   72,   73,   74,   75,   37,   76,
       37,   77,   78,   79,   80,   81,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       82,    1,   83,    1,    1,    1,   84,    1,   85,    1,
        1,    1,   86,    1,    1,    1,    1,    1,   87,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   88,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[89] =
    {   0,
        1,    1,    2,    2,    1,    1,    1,    1,    1,    1,
        3,    3,    1,    1,    1,    1,    1,    3,    4,    4,
        4,    4,    1,    1,    1,    1,    1,    4,    4,    4,
        4,    4,    4,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        1,    1,    1,    1,    5,    4,    4,    4,    4,    4,
        4,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[281] =
    {   0,
        0,    0,  546,  547,  547,  547,  547,   83,  547,  547,
      536,   80,  547,  547,  547,   77,  547,   73,  547,   87,
       87,   93,  518,  547,   75,  547,  517,   65,    0,   90,
       87,   81,   95,   88,   97,  124,   75,  106,  105,  107,
      136,  547,  547,  547,  547,  547,  463,  547,  547,  114,
      547,  537,  547,  530,  529,  528,  547,  153,  505,  512,
      157,  178,  105,  162,    0,  547,  547,  547,  547,    0,
      109,  424,  142,  156,  148,  165,  155,  162,  162,  161,
      158,  169,  161,  424,  162,  178,  172,    0,  180,  194,
      175,  182,  183,  547,  547,  494,  487,  501,  547,  236,

      121,  228,    0,  191,  416,  188,  195,  213,  198,  412,
      219,  216,  413,  480,  406,  218,  232,  407,  237,  234,
      234,  226,  235,  237,  238,  247,  232,  242,  240,  404,
      246,  252,  547,  241,  547,  256,    0,  243,  263,  408,
      257,  257,  272,  273,  362,  273,  277,  286,  329,  276,
      287,  288,  287,  299,  290,    0,  289,  286,    0,  288,
      201,  191,  306,  299,  292,  301,  300,  302,  301,    0,
      547,  309,  318,  318,  332,  188,  329,  325,  325,  333,
      344,  343,  325,  336,    0,  338,    0,    0,  340,  341,
      137,  352,  339,  354,  344,  345,  547,  359,  349,  363,

      353,  547,  355,  127,  366,  362,  364,  368,  387,  369,
        0,    0,    0,  381,  547,  368,  388,  388,  384,    0,
      388,    0,  384,  392,  406,  400,  397,  151,  394,  547,
        0,  395,    0,  397,    0,  412,  409,  406,  417,    0,
      422,  415,  547,  102,  547,  419,    0,    0,  547,  423,
      417,    0,  418,  428,  435,   76,  435,  431,  438,    0,
      435,  443,  434,    0,  547,    0,  442,  547,  453,  547,
      450,  444,  547,  547,  516,  521,  523,  528,  533,  146
    } ;

static yyconst flex_int16_t yy_def[281] =
    {   0,
      274,    1,  274,  274,  274,  274,  274,  275,  274,  274,
      274,  276,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  274,  274,  274,  274,  274,  274,  274,  274,  275,
      274,  275,  274,  274,  274,  276,  274,  274,  278,  279,
      274,  274,  274,  274,  280,  274,  274,  274,  274,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  274,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  274,  274,  278,  274,  279,  274,  274,

      274,  274,  280,  277,  274,  277,  277,  277,  277,  277,
      277,  277,  274,  277,  277,  277,  277,  274,  277,  277,
      274,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  274,  277,  274,  277,  277,  277,  277,  274,
      277,  277,  274,  274,  274,  277,  277,  274,  277,  277,
      274,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      274,  277,  277,  277,  277,  277,  277,  274,  277,  277,
      274,  274,  274,  274,  274,  274,  277,  277,  274,  277,
      277,  274,  277,  277,  277,  277,  277,  277,  277,  274,
      274,  277,  277,  277,  277,  277,  274,  277,  274,  274,

      274,  274,  274,  274,  277,  277,  274,  277,  277,  274,
      277,  277,  277,  277,  274,  274,  277,  277,  277,  277,
      277,  277,  274,  274,  274,  274,  274,  277,  277,  274,
      277,  277,  277,  274,  277,  274,  277,  277,  277,  277,
      274,  274,  274,  274,  274,  277,  277,  277,  274,  274,
      277,  277,  277,  274,  274,  274,  277,  274,  277,  277,
      274,  274,  274,  277,  274,  277,  274,  274,  274,  274,
      274,  274,  274,    0,  274,  274,  274,  274,  274,  274
    } ;

static yyconst flex_int16_t yy_nxt[636] =
    {   0,
        4,    5,    6,    4,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   29,   29,   34,   29,   35,   36,   29,
       37,   38,   29,   39,   40,   29,   29,   41,   29,   29,
       42,   43,   44,   45,   29,   28,   29,   30,   31,   32,
       33,   29,   29,   34,   35,   36,   29,   37,   38,   29,
       39,   40,   29,   29,   41,   29,   29,   46,   47,   48,
       49,    4,    4,    4,    4,    4,    4,    4,   51,   55,
       57,   58,   58,   58,   58,   58,   58,   58,   58,   59,

       67,   68,   71,   61,   60,   62,   62,   62,   62,   61,
       72,   62,   62,   62,   62,   63,   64,   73,   74,   51,
       75,   88,   77,  101,  101,   76,   80,   81,   82,   71,
       78,   56,   83,   89,   52,   65,   90,   72,   91,  101,
      101,   79,  104,   63,   64,   73,   74,   75,   88,  103,
       77,   85,   76,   80,   81,   86,   82,  263,   78,   87,
       83,   89,   65,   92,   90,   52,   91,   93,   79,   61,
      104,   62,   62,   62,   62,  100,  100,  100,  100,   85,
      102,  102,  102,   86,   84,  106,  107,   87,  108,  256,
      109,   92,  112,  110,  111,   93,   62,   62,   62,   62,

      114,  115,  116,  117,  119,  246,  120,  122,  124,  227,
      123,  125,  106,  107,  130,  136,  108,  109,  216,  112,
      110,  128,  111,  126,  127,  131,  132,  114,  115,  116,
      117,  134,  119,  120,  122,  137,  124,  123,  125,  129,
      138,  130,  113,  136,  139,  118,  102,  102,  102,  128,
      126,  127,  131,  132,  100,  100,  100,  100,  134,  141,
      142,  146,  137,  147,  149,  150,  129,  151,  138,  152,
      153,  139,  154,  155,  156,  204,  157,  158,  191,  159,
      160,  162,  163,  190,  164,  165,  141,  142,  146,  166,
      167,  147,  149,  150,  169,  151,  152,  170,  153,  171,

      154,  155,  156,  157,  172,  158,  159,  160,  177,  162,
      163,  164,  178,  165,  173,  179,  166,  174,  167,  181,
      175,  169,  182,  183,  170,  184,  185,  171,  186,  187,
      188,  189,  172,  192,  193,  198,  177,  194,  195,  196,
      178,  173,  197,  179,  174,  201,  181,  175,  199,  202,
      182,  183,  184,  200,  185,  186,  187,  188,  189,  203,
      207,  192,  193,  198,  194,  195,  196,  205,  206,  197,
      208,  209,  210,  201,  211,  199,  212,  202,  213,  214,
      200,  215,  217,  180,  218,  219,  222,  203,  207,  220,
      221,  223,  224,  228,  205,  206,  225,  208,  226,  209,

      210,  211,  229,  212,  230,  213,  214,  231,  215,  234,
      217,  218,  235,  219,  222,  236,  220,  221,  223,  237,
      224,  228,  232,  225,  233,  226,  238,  239,  240,  229,
      241,  230,  242,  243,  231,  244,  234,  245,  247,  248,
      235,  249,  236,  250,  251,  176,  252,  237,  253,  254,
      232,  233,  255,  238,  239,  240,  257,  241,  258,  242,
      259,  243,  260,  244,  245,  247,  248,  261,  249,  262,
      268,  250,  251,  252,  264,  265,  253,  254,  266,  255,
      267,  269,  270,  257,  271,  272,  258,  259,  273,  260,
      168,  161,  148,  145,  261,  144,  143,  262,  268,  140,

      135,  264,  265,   99,  133,  266,   97,  267,  269,  270,
      121,  105,  271,  272,   99,  273,   50,   97,   50,   50,
       50,   54,   54,   54,   54,   54,   70,   70,   96,   96,
      274,   96,   96,   98,   98,   98,   98,   98,   95,   95,
       50,   94,   69,   66,   53,  274,    3,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,

      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274
    } ;

static yyconst flex_int16_t yy_chk[636] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    8,   12,
       16,   18,   18,   18,   18,   16,   16,   16,   16,   20,

       25,   25,   28,   21,   20,   21,   21,   21,   21,   22,
       28,   22,   22,   22,   22,   21,   21,   30,   31,   50,
       32,   37,   33,   63,   63,   32,   34,   34,   35,   28,
       33,   12,   35,   38,    8,   21,   39,   28,   40,  101,
      101,   33,   71,   21,   21,   30,   31,   32,   37,  280,
       33,   36,   32,   34,   34,   36,   35,  256,   33,   36,
       35,   38,   21,   41,   39,   50,   40,   41,   33,   58,
       71,   58,   58,   58,   58,   61,   61,   61,   61,   36,
       64,   64,   64,   36,   35,   73,   73,   36,   74,  244,
       75,   41,   77,   75,   76,   41,   62,   62,   62,   62,

       78,   79,   80,   81,   82,  228,   83,   85,   86,  204,
       85,   87,   73,   73,   91,  106,   74,   75,  191,   77,
       75,   90,   76,   89,   89,   92,   93,   78,   79,   80,
       81,  104,   82,   83,   85,  107,   86,   85,   87,   90,
      108,   91,   77,  106,  109,   81,  102,  102,  102,   90,
       89,   89,   92,   93,  100,  100,  100,  100,  104,  111,
      112,  116,  107,  117,  119,  120,   90,  121,  108,  122,
      123,  109,  124,  125,  126,  176,  127,  128,  162,  128,
      129,  131,  132,  161,  134,  136,  111,  112,  116,  138,
      139,  117,  119,  120,  141,  121,  122,  142,  123,  143,

      124,  125,  126,  127,  144,  128,  128,  129,  146,  131,
      132,  134,  147,  136,  144,  148,  138,  144,  139,  150,
      144,  141,  151,  152,  142,  153,  154,  143,  155,  157,
      158,  160,  144,  163,  164,  169,  146,  165,  166,  167,
      147,  144,  168,  148,  144,  173,  150,  144,  172,  174,
      151,  152,  153,  172,  154,  155,  157,  158,  160,  175,
      179,  163,  164,  169,  165,  166,  167,  177,  178,  168,
      180,  181,  182,  173,  183,  172,  184,  174,  186,  189,
      172,  190,  192,  149,  193,  194,  198,  175,  179,  195,
      196,  199,  200,  205,  177,  178,  201,  180,  203,  181,

      182,  183,  206,  184,  207,  186,  189,  208,  190,  210,
      192,  193,  214,  194,  198,  216,  195,  196,  199,  217,
      200,  205,  209,  201,  209,  203,  218,  219,  221,  206,
      223,  207,  224,  225,  208,  226,  210,  227,  229,  232,
      214,  234,  216,  236,  237,  145,  238,  217,  239,  241,
      209,  209,  242,  218,  219,  221,  246,  223,  250,  224,
      251,  225,  253,  226,  227,  229,  232,  254,  234,  255,
      262,  236,  237,  238,  257,  258,  239,  241,  259,  242,
      261,  263,  267,  246,  269,  271,  250,  251,  272,  253,
      140,  130,  118,  115,  254,  114,  113,  255,  262,  110,

      105,  257,  258,   98,   97,  259,   96,  261,  263,  267,
       84,   72,  269,  271,   60,  272,  275,   59,  275,  275,
      275,  276,  276,  276,  276,  276,  277,  277,  278,  278,
       56,  278,  278,  279,  279,  279,  279,  279,   55,   54,
       52,   47,   27,   23,   11,    3,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,

      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "analisador_lexico.l"
#line 2 "analisador_lexico.l"
#include <stdio.h>
#include <string.h>
#include "hash.h"
int i = 0;
int num_linha = 1;
int escopo;
char c;
char comentario[2000];
char identificador[100];
char expressao[2000];
int tipo;

#line 704 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 16 "analisador_lexico.l"




#line 896 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 275 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 547 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 20 "analisador_lexico.l"
{return token_pr_algoritmo;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 21 "analisador_lexico.l"
{escopo = 1;return token_pr_variaveis;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 22 "analisador_lexico.l"
{return token_pr_fim_variaveis;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 23 "analisador_lexico.l"
{return token_pr_inicio;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 24 "analisador_lexico.l"
{return token_pr_fim;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 25 "analisador_lexico.l"
{tipo = 0; return token_pr_inteiro;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 26 "analisador_lexico.l"
{return token_pr_inteiros;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 27 "analisador_lexico.l"
{tipo = 1; return token_pr_caractere;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 28 "analisador_lexico.l"
{return token_pr_caracteres;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 29 "analisador_lexico.l"
{tipo = 3; return token_pr_real;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 30 "analisador_lexico.l"
{return token_pr_reais;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 31 "analisador_lexico.l"
{tipo = 2; return token_pr_literal;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 32 "analisador_lexico.l"
{return token_pr_literais;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 33 "analisador_lexico.l"
{return token_pr_logico;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 34 "analisador_lexico.l"
{return token_pr_logicos;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 35 "analisador_lexico.l"
{return token_pr_matriz;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 36 "analisador_lexico.l"
{return token_pr_se;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 37 "analisador_lexico.l"
{return token_pr_entao;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 38 "analisador_lexico.l"
{return token_pr_senao;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 39 "analisador_lexico.l"
{return token_pr_fim_se;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 40 "analisador_lexico.l"
{return token_pr_para;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 41 "analisador_lexico.l"
{return token_pr_de;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 42 "analisador_lexico.l"
{return token_pr_ate;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 43 "analisador_lexico.l"
{return token_pr_faca;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 44 "analisador_lexico.l"
{return token_pr_fim_para;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 45 "analisador_lexico.l"
{return token_pr_passo;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 46 "analisador_lexico.l"
{return token_pr_enquanto;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 47 "analisador_lexico.l"
{return token_pr_fim_enquanto;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 48 "analisador_lexico.l"
{return token_pr_imprima;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 49 "analisador_lexico.l"
{return token_pr_imprima_ln;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 50 "analisador_lexico.l"
{return token_pr_leia;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 51 "analisador_lexico.l"
{return token_pr_leia_ln;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 52 "analisador_lexico.l"
{return token_pr_maximo;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 53 "analisador_lexico.l"
{return token_pr_minimo;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 54 "analisador_lexico.l"
{return token_pr_media;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 55 "analisador_lexico.l"
{escopo = 0;return token_pr_funcao;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 56 "analisador_lexico.l"
{return token_pr_retorne;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 57 "analisador_lexico.l"
{return token_pr_verdadeiro;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 58 "analisador_lexico.l"
{return token_pr_falso;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 59 "analisador_lexico.l"
{return token_pr_e;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 60 "analisador_lexico.l"
{return token_pr_ou;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 62 "analisador_lexico.l"
{return token_pr_escolha;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 63 "analisador_lexico.l"
{return token_pr_caso;}	
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 64 "analisador_lexico.l"
{return token_pr_fim_escolha;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 65 "analisador_lexico.l"
{return token_pr_default;}
	YY_BREAK
case 46:
#line 69 "analisador_lexico.l"
case 47:
#line 70 "analisador_lexico.l"
case 48:
#line 71 "analisador_lexico.l"
case 49:
YY_RULE_SETUP
#line 71 "analisador_lexico.l"
{return token_inteiro;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 72 "analisador_lexico.l"
{return token_real;}
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 73 "analisador_lexico.l"
{return token_caractere;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 74 "analisador_lexico.l"
{return token_literal;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 75 "analisador_lexico.l"
{return token_soma;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 76 "analisador_lexico.l"
{return token_subtracao;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 77 "analisador_lexico.l"
{return token_divisao;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 78 "analisador_lexico.l"
{return token_multiplicacao;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 79 "analisador_lexico.l"
{return token_incrementador;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 80 "analisador_lexico.l"
{return token_modulo;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 81 "analisador_lexico.l"
{return token_maior;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 82 "analisador_lexico.l"
{return token_maior_igual;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 83 "analisador_lexico.l"
{return token_menor;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 84 "analisador_lexico.l"
{return token_menor_igual;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 85 "analisador_lexico.l"
{return token_igual;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 86 "analisador_lexico.l"
{return token_diferente;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 87 "analisador_lexico.l"
{return token_e;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 88 "analisador_lexico.l"
{return token_e_bit;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 89 "analisador_lexico.l"
{return token_ou;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 90 "analisador_lexico.l"
{return token_ou_bit;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 91 "analisador_lexico.l"
{return token_xor_bit;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 92 "analisador_lexico.l"
{return token_nao;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 93 "analisador_lexico.l"
{return token_til;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 94 "analisador_lexico.l"
{return token_aspas_dupla;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 95 "analisador_lexico.l"
{return token_aspas_simples;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 96 "analisador_lexico.l"
{return token_abre_parenteses;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 97 "analisador_lexico.l"
{return token_fecha_parenteses;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 98 "analisador_lexico.l"
{return token_abre_chaves;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 99 "analisador_lexico.l"
{return token_fecha_chaves;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 100 "analisador_lexico.l"
{return token_abre_colchetes;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 101 "analisador_lexico.l"
{return token_fecha_colchetes;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 102 "analisador_lexico.l"
{return token_tralha;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 103 "analisador_lexico.l"
{return token_contra_barra;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 104 "analisador_lexico.l"
{return token_ponto;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 105 "analisador_lexico.l"
{return token_virgula;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 106 "analisador_lexico.l"
{return token_ponto_virgula;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 107 "analisador_lexico.l"
{return token_dois_pontos;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 108 "analisador_lexico.l"
{return token_atribuicao;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 109 "analisador_lexico.l"
{
	
	strcpy(identificador,yytext);	
	expressao[strlen(expressao)] = '-';
	i=0;
	c = yytext[i];
	while(c!='\0'){
		expressao[strlen(expressao)] = c;
		i++;
		c = yytext[i];
	}
	expressao[strlen(expressao)]='\0';
	return token_identificador;
} 
	YY_BREAK
case 88:
/* rule 88 can match eol */
YY_RULE_SETUP
#line 124 "analisador_lexico.l"
{num_linha++;}
	YY_BREAK
case 89:
/* rule 89 can match eol */
YY_RULE_SETUP
#line 125 "analisador_lexico.l"
{
	strcpy(comentario,yytext);
	for(i=0; i<strlen(comentario); i++){
		if(comentario[i] == '\n')
			num_linha++;	
	}
}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 133 "analisador_lexico.l"
;
	YY_BREAK
case 91:
/* rule 91 can match eol */
YY_RULE_SETUP
#line 134 "analisador_lexico.l"
{num_linha++;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 136 "analisador_lexico.l"
{return token_desconhecido;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 138 "analisador_lexico.l"
ECHO;
	YY_BREAK
#line 1458 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 275 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 275 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 274);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 138 "analisador_lexico.l"



